name: "Backend Update"

on:
  push:
    branches: 
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BACKENDKEY }}
          
        run: |
          echo "$AWS_SECRET_ACCESS_KEY" > backendKey.pem 
          chmod 600 backendKey.pem

      - name: Deploy to EC2
        run: |
          # Define EC2 instance details
          INSTANCE_ID="i-01a1687bcecec6d30" 
          # An elastic IP was allocated to the EC2 instance
          PUBLIC_IP=98.84.73.133

          # SSH into the EC2 instance
          ssh -o StrictHostKeyChecking=no -i backendKey.pem ubuntu@$PUBLIC_IP << 'EOF'
            # Exit if error occurs
            set -e
            # Navigate to pRecipe App directory
            cd /home/ubuntu/BookCatalogue
            # Pull repository state to vm
            git pull origin master
            
            # Kill the server if one is running
            pkill -f "rails server" || true
            
            # Install dependencies, migrate the database, and Start the application
            # When the application would start - the workflow would run until the rails server was terminated.
            sudo gem install bundler  # Install bundler if not already installed
            bundle install
            rails db:migrate
            #RAILS_ENV=production sudo /home/ubuntu/.rbenv/shims/rails server --binding 0.0.0.0 --port 80
          EOF

      - name: Clean up
        run: |
          # Remove the private key after use
          rm -f backendKey.pem